version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:1488322@db:5432/goodsdb?sslmode=disable
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1488322
      - POSTGRES_DB=goodsdb
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    entrypoint: ["docker-entrypoint.sh"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
