wipe     = true
no-tests = true
add-enum-types = true

[psql]
dbname = "goodsdb"
host   = "localhost"
port   = 5432
user   = "postgres"
pass   = "1488322"
schema = "public"
blacklist = ["migrations", "other"]