POST http://localhost:8080/upload
Content-Type: application/json

{
  "Url": "https://cdn.discordapp.com/attachments/1061032871785136158/1061046650463850537/goods_update.xlsx",
  "seller_id": "1"
}

###

