name: Go GRPC Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -o app
      
    - name: Tests
      run: go test 

    - name: Build Docker Image
      run: |
        docker-compose up --build
        docker-compose down
